name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Atualiza todos os dias
  workflow_dispatch: # Para rodar manualmente quando quiser

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependências
        run: npm install axios

      - name: Executar script para atualizar README
        run: node generate-repos.js

      - name: Commit e push das alterações
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git commit -m 'Atualiza README automaticamente com a lista de repositórios'
          git push
